name: Fetch Pierce Addresses

on:
  schedule:
    - cron: '0 12 * * *'  # Runs daily at midnight UTC
  workflow_dispatch:  # Allows for manual trigger

jobs:
  fetch_addresses:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests

      - name: Run the address-fetching script
        run: python address.py

      - name: Commit and push output
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git push -f origin main
          git add pierce_addresses.txt
          git commit -m "Update pierce_addresses.txt"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
