name: Save The Address

on:
  schedule:
    - cron: '5,10,15 * * * *'  # Runs daily at midnight UTC
  workflow_dispatch:  # Allows for manual trigger     
    inputs:
      reason:
        description: 'Motivo esecuzione del flusso di lavoro'
        required: true
        default: 'Esecuzione manuale'

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Imposta Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'  # Specifica la versione di Python

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests

    - name: Esegui script Python
      run: python address.py
      
    - name: Configura Git
      run: |
        git config --local user.name "GitHub Action"
        git config --local user.email "action@github.com"

    - name: Aggiungi e committa pierce_addresses.txt
      run: |
        # git push -f origin main
        git add pierce_addresses.txt
        git commit -m "Aggiornato pierce_addresses.txt"
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
