name: Save The Date

on:
  push:
    branches:
      - main  # Cambia il nome del branch se necessario

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Imposta Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'  # Specifica la versione di Python

    - name: Esegui script Python
      run: python saveTheDate.py
