name: Save The Date

on:
  push:
    branches:
      - main  # Cambia il nome del branch se necessario

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Imposta Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'  # Specifica la versione di Python

    - name: Esegui script Python
      run: python saveTheDate.py
      
    - name: Configura Git
      run: |
        git config --local user.name "GitHub Action"
        git config --local user.email "action@github.com"

    - name: Aggiungi e committa dataora.txt 2
      run: |
        git push -f origin main
        git add dataora.txt
        git commit -m "Aggiornato dataora.txt con la data e ora correnti"
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
